# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Diego Cardoso
title: Data & Analytics Leader Sr
email: talktocardoso@gmail.com
# website:

# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username:
github_username: dicardos
# stackoverflow_username: "00000001"
# dribbble_username:
# facebook_username:
# flickr_username:
# instagram_username:
linkedin_username: diego-cardoso-04689b34
# xing_username:
# pinterest_username:
# youtube_username:
# googleplus_username: +
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
  - title: itsgoingto.be
    icon: fas fa-globe
    url: https://medium.com/@diegocardoso_41218
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/diego_foto.jpeg
about_content: |
  Write an awesome description about yourself here, this supports markdown, so you can add [links](http://foobar.com) and highlight things <mark>like this</mark>.

  You can even add paragraphs by using empty lines like this and add anything else [markdown](https://www.markdownguide.org/getting-started#what-is-markdown) supports such as
    - Lists
    - Tables

content:
  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Santander
        link: https://www.santander.com.br/
        # link_text: boringcompany.com
        sub_title: Senior Network System Administrator
        caption: March 2019 - Present
        quote: 
        description: |
          Every company needs its networks properly administered and The Boring Company is no exception. Digging holes is hard and I play my part making sure the whole company stays connected. I lead a team of 5 people and enjoy driving the company to try new technologies.

      - layout: left
        title: Vivo
        link: https://www.telefonica.com.br/
        # link_text: boringcompany.com
        sub_title: Senior Network System Administrator
        caption: July 2016 - February 2019
        quote: 
        description: |
          Every company needs its networks properly administered and The Boring Company is no exception. Digging holes is hard and I play my part making sure the whole company stays connected. I lead a team of 5 people and enjoy driving the company to try new technologies.

      - layout: left
        title: Raízen
        link: https://www.raizen.com.br/
        # link_text: boringcompany.com
        sub_title: Senior Network System Administrator
        caption: January 2016 - June 2016
        quote: 
        description: |
          Every company needs its networks properly administered and The Boring Company is no exception. Digging holes is hard and I play my part making sure the whole company stays connected. I lead a team of 5 people and enjoy driving the company to try new technologies.

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: University of São Paulo (USP)
        caption: 2021 - 2023
        sub_title: MSc Electrical Engineering
        quote: 
        description: |
          During my time at Harvard I learnt most of my key skills that have I have taken through my career such as teamwork and working to tight deadlines. I thoroughly enjoyed my time as university and learnt a lot about a healthy work life balance.

          I spent a lot of my free time as a committee member of the *Harvard Mountaineering Club* taking on roles such as *Trip Secretary* and *Vice-President*.
      
      - layout: left
        title: University of Manitoba (UofM)
        caption: 2013 - 2014
        sub_title: BSc Statistics
        quote: 
        description: |
          During my time at Harvard I learnt most of my key skills that have I have taken through my career such as teamwork and working to tight deadlines. I thoroughly enjoyed my time as university and learnt a lot about a healthy work life balance.

          I spent a lot of my free time as a committee member of the *Harvard Mountaineering Club* taking on roles such as *Trip Secretary* and *Vice-President*.
      
      - layout: left
        title: Federal University of São Carlos (UFSCar)
        caption: 2010 - 2015
        sub_title: BSc Statistics
        quote: 
        description: |
          During my time at Harvard I learnt most of my key skills that have I have taken through my career such as teamwork and working to tight deadlines. I thoroughly enjoyed my time as university and learnt a lot about a healthy work life balance.

          I spent a lot of my free time as a committee member of the *Harvard Mountaineering Club* taking on roles such as *Trip Secretary* and *Vice-President*.

  - title: A Little More About Me
    layout: text
    content: |
      Alongside my interests in networks and software engineering some of my other interests and hobbies are:
      - Rock climbing
      - Gaming
      - Knitting
      - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

      Look at this cool image  
      ![Trees](/modern-resume-theme/images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-seo-tag
