# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Diego Cardoso
title: Data & Analytics Leader Sr
email: talktocardoso@gmail.com
# website:

# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username:
github_username: dicardos
# stackoverflow_username: "00000001"
# dribbble_username:
# facebook_username:
# flickr_username:
# instagram_username:
linkedin_username: diego-cardoso-04689b34
# xing_username:
# pinterest_username:
# youtube_username:
# googleplus_username: +
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
  - title: itsgoingto.be
    icon: fas fa-globe
    url: https://medium.com/@diegocardoso_41218
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/diego_foto.jpeg
about_content: |
  Hi, my name is Diego Cardoso. I’m a Data & Analytics Leader with a strong foundation in statistical analysis and data science projects. I hold a BSc in Statistics from the Federal University of São Carlos (UFSCar), with a sandwich program at the University of Manitoba (UofM), and an MSc in Electrical Engineering from the University of São Paulo (Poli-USP). With over 9 years of experience, my professional journey has included pivotal roles in the banking, telecommunications, and energy sectors.

  Currently, I am working at Santander as a Data & Analytics Leader. I lead initiatives focused on developing data-driven strategies, optimizing customer insights, and enhancing portfolio profitability. My responsibilities include overseeing the creation of predictive models, driving cross-functional data projects, and mentoring a team of data professionals.
  
  I am passionate about leveraging data to inform strategic decisions and enhance operational efficiencies. I specialize in applying my knowledge to solve complex business problems, driving innovative solutions that deliver measurable results.

content:
  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Santander Brasil
        link: https://www.santander.com.br/
        sub_title: Data & Analytics Leader Sr
        caption: March 2019 - Present
        quote: 
        description: |
          I have extensive experience in data and analytics, having held various roles at Santander, including Data Scientist, Consultant, Coordinator, and Manager. I began working with vehicle financing, where I led several data projects involving customer, product, and offer analysis to increase portfolio profitability and identify cross-selling opportunities. Subsequently, I moved to the CRM B2B department, specializing in the Small and Mid-size Enterprise (SME) segment. Currently, within the CRM team, I am responsible for analytics and modeling, developing data-driven strategies to provide actionable insights for SMEs.

      - layout: left
        title: Vivo (Telefônica Brasil)
        link: https://www.telefonica.com.br/
        sub_title: Senior Data Scientist
        caption: July 2016 - February 2019
        quote: 
        description: |
           During my time at Vivo (Telefônica Brasil), I analyzed large datasets to identify trends and insights, developed and maintained dashboards for real-time data visualization, and conducted in-depth analysis to understand customer behavior and preferences. I developed Machine Learning models to classify customers who are more likely to purchase mobile phone products, constructed the Next Best Offer algorithm to define sales offers, and developed credit scores using telco data. Additionally, I worked through business cases and played the role of a consultant focusing on monetizing telco data by identifying and creating new revenue streams.

      - layout: left
        title: Raízen
        link: https://www.raizen.com.br/
        sub_title: Intern
        caption: January 2016 - June 2016
        quote: 
        description: |
          During my internship, I developed Machine Learning models to predict sugarcane mill output, total recoverable sugar content (TRS), and tonnes of sugarcane per hectare (TCH). I also utilized clustering techniques and descriptive statistical analysis to evaluate planting failures using unmanned aerial vehicle (UAV) images.
          
  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: University of São Paulo (USP)
        caption: 2021 - 2023
        sub_title: MSc Electrical Engineering
        quote: 
        description: |
          During my master's program at University of São Paulo, I focused on advanced research and practical applications in the field of statistical signal processing and machine learning. I conducted in-depth research on air pollution, developing innovative solutions to estimate ground-level ozone and explain its behavior over time. My dissertation provided valuable insights into the temporal dynamics and influencing factors of ozone levels
      - layout: left
        title: University of Manitoba (UofM)
        caption: 2013 - 2014
        sub_title: BSc Statistics
        quote: 
        description: |
          During my time at the University of Manitoba as part of the Science Without Borders program, I embraced the opportunity to immerse myself in a new cultural and academic environment. This experience enhanced my adaptability and cross-cultural communication skills, which are invaluable in today's globalized work environment.
      - layout: left
        title: Federal University of São Carlos (UFSCar)
        caption: 2010 - 2015
        sub_title: BSc Statistics
        quote: 
        description: |
          During my time at the Federal University of São Carlos, I pursued a rigorous academic curriculum that provided the groundwork for my career in data and analytics. My activities and achievements included: advanced coursework, research projects and extracurricular involvement. I conducted a scientific initiation project funded by the PBIC scholarship program. This experience allowed me to deepen my understanding of statistical methods and gain valuable hands-on experience in data analysis.
  - title: A Little More About Me
    layout: text
    content: |
      Hello! I hold Brazilian and Spanish/European citizenship, allowing me to embrace diverse cultural and linguistic experiences. I have a keen interest in emerging technologies and enjoy outdoor sports such as hiking and rock climbing. I am passionate about continuous learning and constantly exploring new programming languages, including Python, JavaScript, and SQL. I thrive on challenges that push me to expand my horizons and apply my creativity.
      - Rock climbing
      - Gaming
      - Knitting
      - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)


# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-seo-tag
